spring:
  datasource:
    url: jdbc:mysql://3.34.198.174:3306/kbnb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: jbs
#  datasource:
#    url: jdbc:mysql://localhost:3306/kbnb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#    username: root
#    password: 12341234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 280572023320-ahrevqr0tt474su1o1a7qm1oja5vlled.apps.googleusercontent.com
            clientSecret: chB7l-RK5GINE0pDojbWjsHB
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect

cloud:
  aws:
    s3:
      bucket: kbnbbucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true