spring:
  datasource:
    url: jdbc:mysql://mysql-1.cfmbtwavrtjc.ap-northeast-2.rds.amazonaws.com:3306/kbnb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: jbs12341234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 280572023320-ahrevqr0tt474su1o1a7qm1oja5vlled.apps.googleusercontent.com
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect

cloud:
  aws:
    s3:
      bucket: pungdong
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true

bootPay:
  applicationId: 6024e5ee5b2948001d52037e
  privateKey: n53GEUAuH4NuHjmsPhYJ5Um1N/Tf2K7eWy1w01iF7A8=