spring:
  datasource:
    url: jdbc:mysql://mysql-1.cfmbtwavrtjc.ap-northeast-2.rds.amazonaws.com:3306/kbnb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: jbs12341234