= DIVING REST API Guide
김예찬;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= 개요

[[overview-http-verbs]]
== HTTP 동사

본 REST API에서 사용하는 HTTP 동사(verbs)는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 동사 | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

| `PUT`
| 기존 리소스를 수정할 때 사용

| `PATCH`
| 기존 리소스의 일부를 수정할 때 사용

| `DELETE`
| 기존 리소스를 삭제할 떄 사용
|===

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함. 응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있다.

| `204 No Content`
| 기존 리소스를 성공적으로 수정함.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우. 응답 본문에 더 오류에 대한 정보가 담겨있다.

| `404 Not Found`
| 요청한 리소스가 없음.
|===

[[overview-errors]]
== 오류

에러 응답이 발생했을 때 (상태 코드 >= 400), 본문에 해당 문제를 기술한 JSON 객체가 담겨있다. 에러 객체는 다음의 구조를 따른다.

예를 들어, 잘못된 요청으로 이벤트를 만들려고 했을 때 다음과 같은 `400 Bad Request` 응답을 받는다.

[[errors-email-duplication]]
=== 이메일 중복 예외
operation::exception-emailDuplication[snippets='response-body,response-fields']

=== 이메일 패스워드 틀림 예외
operation::exception-emailOrPasswordWrong[snippets='response-body,response-fields']

[[overview-hypermedia]]
== 하이퍼미디어

본 REST API는 하이퍼미디어와 사용하며 응답에 담겨있는 리소스는 다른 리소스에 대한 링크를 가지고 있다.
응답은 http://stateless.co/hal_specification.html[Hypertext Application from resource to resource. Language (HAL)] 형식을 따른다.
링크는 `_links`라는 키로 제공한다. 본 API의 사용자(클라이언트)는 URI를 직접 생성하지 않아야 하며, 리소스에서 제공하는 링크를 사용해야 한다.

[[resources]]
= 리소스

[[resources-index]]
== 인덱스

인덱스는 서비스 진입점을 제공한다.


[[resources-index-access]]
=== 인덱스 조회

`GET` 요청을 사용하여 인덱스에 접근할 수 있다.

[[resource-user]]
== 유저

유저를 생성하거나 로그인 및 로그아웃 조회할 때 사용한다

[[resource-user-signup-email]]
=== 이메일 회원가입
operation::auth-signup-email[]

[[resource-user-login-email]]
=== 이메일 로그인
operation::auth-login-email[]

[[resource-user-get-me]]
=== 유저 정보 조회
operation::user-get-me[]

[[resource-room]]
== 숙소

숙소에 대한 상세조회, 리스트 조회, 등록, 삭제, 찜하기등을 할때 사용한다

[[resource-room-get-list-by-condition]]
=== 숙소 리스트 조건 검색
operation::room-get-roomList-by-condition[]

[[resource-room-get-detail]]
=== 숙소 상세 검색
operation::room-get-detail[]

[[resource-room-check]]
=== 찜하기 찜하기 취소
operation::room-check[]

[[resource-reservation]]
== 예약

[[resource-reservation-register]]
=== 예약 등록
operation::reservation-register[]

[[resource-reservation-lookupList]]
=== 예약 리스트 조회
operation::reservation-lookupList[]

